# **EDA Notebook**

---
## 0. Setup Environment

In [1]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 56.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 47.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Mounted at /content/gdrive

You can now save your data files in: /content/gdrive/MyDrive/36106/assignment/AT3/data

---
## Student Information

In [ ]:
group_name = ""
student_name = "Yi An Tsai"
student_id = "25532767"

In [ ]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [ ]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [ ]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [ ]:
# <Student to fill this section>

### 0.b Import Packages

In [ ]:
# <Student to fill this section>
import pandas as pd
import altair as alt

---
## B. Data Understanding

In [ ]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "unit_measure.csv")
except Exception as e:
  print(e)

### B.1 Explore Dataset

In [ ]:
df.head()

                      unit_measure_code      name
0  ee0468c7-6417-489a-b233-da57ab966174     Boxes
1  7768b253-7430-402f-b90f-1e025c57459b    Bottle
2  1f485b4e-fc4d-47b2-ab57-af19b21eee40   Celsius
3  e87c6cb9-24ca-405a-996c-8f59ab7730fa  Canister
4  91fa7aa6-72aa-40a6-822f-8b80aa9f6376    Carton

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   unit_measure_code  38 non-null     object
 1   name               38 non-null     object
dtypes: object(2)
memory usage: 740.0+ bytes

In [ ]:
df.shape   # 38 rows and 2 columns

(38, 2)

In [ ]:
len(df['unit_measure_code'].unique())

38

In [ ]:
len(df['name'].unique())

38

In [ ]:
df['unit_measure_code'].value_counts()

unit_measure_code
ee0468c7-6417-489a-b233-da57ab966174    1
7768b253-7430-402f-b90f-1e025c57459b    1
1f485b4e-fc4d-47b2-ab57-af19b21eee40    1
e87c6cb9-24ca-405a-996c-8f59ab7730fa    1
91fa7aa6-72aa-40a6-822f-8b80aa9f6376    1
1f5f8ee7-58c4-4c4e-b8db-b7c1025b3400    1
b4c6422a-e170-4911-852f-38a7c19f5573    1
5c3d2f68-8573-4e53-8c4e-a72a5f92518e    1
e2e52698-ce31-4fb2-866f-bcffbdfd3147    1
7d2f574f-2c4b-45e5-bb2e-7c74c247492c    1
44f61043-62cb-4dea-a921-edf1df4b6a39    1
609a70c5-01f5-48f0-9939-4f04449e2018    1
0cc915c9-7473-4676-afff-2a4d4f023594    1
28bd7d2e-b75a-40dc-b62f-f360a9de2559    1
75fa117b-bb26-4752-8ec5-771acf4c50f6    1
8dbf3502-309f-4636-9f3e-1ae1cabc748b    1
cf068cf8-e6f9-4956-b31b-1d6eb91f3c5c    1
8c4f020f-f9c1-492b-8395-1372b7bda7a7    1
acbdd92d-1e1f-4ba8-a695-3f0c82d87759    1
7cca3216-2076-4b76-b746-8d4a33c94222    1
8dae8c54-6149-48bd-a0e1-9050f4ee82b6    1
d8954392-48a0-4cce-af48-15a83ab47274    1
ee700422-0d9b-48c5-ae33-d08b8b5034bf    1
57ee0c60-3085-4d9c-bae2-26022aa2d447    1
aea9d8c5-cf48-46e0-afa3-f36c6cf44c4e    1
c4797df8-be0b-4d3a-a6c4-0f1765f0a822    1
dd058911-cfcb-4c19-9df7-a8f40bbccf13    1
ee1d7851-244e-47db-8960-bced186cccad    1
8cb5f9fe-f273-42f3-96e4-1f93e26bb318    1
b0a224d6-adce-4062-b701-32d569ddaa05    1
3fbce844-926c-442f-87d9-9017094ed6b7    1
1316d404-c512-49da-bfb6-f6df816570ef    1
5c50e872-03a3-4aa1-8d0a-103cdf0fc00d    1
6ad6e4b7-e1c2-42f2-90f6-306f08b41623    1
2eb286e8-8050-4cf5-a260-fd2cedb6e1f4    1
5885bdb8-189e-4001-9f96-9cffd780b130    1
14266c5d-bb1d-4b58-9d8d-f13f6eb35863    1
a24c076e-f88e-44e9-811b-b4a3da40d463    1
Name: count, dtype: int64

In [ ]:
df['name'].value_counts()

name
Boxes                   1
Bottle                  1
Celsius                 1
Canister                1
Carton                  1
Cubic meters            1
Cubic centimeter        1
Cubic decimeter         1
Centimeter              1
Square centimeter       1
Crate                   1
Case                    1
Container               1
Decimeter               1
Dozen                   1
Each                    1
Cubic foot              1
Gram                    1
Gallon                  1
Inch                    1
Kilogram                1
Kilogram/cubic meter    1
Kilometer               1
Kiloton                 1
Liter                   1
US pound                1
Meter                   1
Square meter            1
Cubic meter             1
Milligram               1
Milliliter              1
Millimeter              1
Ounces                  1
Pack                    1
Pallet                  1
Piece                   1
Percentage              1
Pint, US liquid         1
Name: count, dtype: int64

In [ ]:
dataset_insights = """
There are 38 rows and 2 columns in the dataset, without missing values.
This dataset includes 38 unique unit_measure_code and 38 unique name.
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `\<put feature name here\>`

In [ ]:
feature_1_insights = """
There isn’t any meaningful feature here, as these two columns simply represent the same information, the unique code and its corresponding name.
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)