# **EDA Notebook**

---
## 0. Setup Environment

In [ ]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 27.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 38.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Mounted at /content/gdrive

You can now save your data files in: /content/gdrive/MyDrive/36106/assignment/AT3/data

---
## Student Information

In [ ]:
# <Student to fill this section>
group_name = "Group 20"
student_name = "Ratnadeep Patra"
student_id = "26294153"

In [ ]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [ ]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [ ]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [ ]:
# <Student to fill this section>

### 0.b Import Packages

In [ ]:
# <Student to fill this section>
import pandas as pd
import altair as alt

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

---
## B. Data Understanding

In [ ]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "product_sub_category.csv")
except Exception as e:
  print(e)

### B.1 Explore Dataset

In [ ]:
pd.set_option('display.max_columns', None) # Forcing pandas to display all columns
pd.set_option('display.max_rows', None) # Forcing pandas to display all rows

In [ ]:
df.describe(include='all').T

                       count unique                                   top freq
product_subcategory_id    37     37  5332b46f-2ec0-453b-8237-c78051d4c7bf    1
product_category_id       37      4  65e2841b-c7da-4c4a-9565-cd8cfd9a2f68   14
name                      37     37                        Mountain Bikes    1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_subcategory_id  37 non-null     object
 1   product_category_id     37 non-null     object
 2   name                    37 non-null     object
dtypes: object(3)
memory usage: 1020.0+ bytes

In [ ]:
df['name'].sample(10)

2       Touring Bikes
34           Panniers
36    Tires and Tubes
8         Derailleurs
13        Road Frames
26        Bike Stands
24              Vests
7           Cranksets
4     Bottom Brackets
12             Pedals
Name: name, dtype: object

In [ ]:
dataset_insights = """
This dataset contains information about product subcategories, with 37 entries and 3 columns. There are no missing values across any of the columns. The
columns are : 'product_subcategory_id' - unique identifier for each product subcategory (acting as primark key); 'product_category_id' - identifier for
the parent product category (4 unique values); and 'name' - the name of the product subcategory (37 unique values). The dataset essentially maps unique
product subcategories to their respective product categories.
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `product_category_id`

In [ ]:
for csv_file in os.listdir(at.folder_path):
    if 'product_category_id' in pd.read_csv(at.folder_path / csv_file).columns:
        print(csv_file)

product_category.csv
product_sub_category.csv

In [ ]:
# <Student to fill this section>
feature_1_insights = """
The 'product_category_id' is a categorical feature with 4 unique values. It serves as a foreign key to the 'product_category.csv' dataset, where further
details about each product category can be found.
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)