# **EDA Notebook**

---
## 0. Setup Environment

In [ ]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 38.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 37.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Mounted at /content/gdrive

You can now save your data files in: /content/gdrive/MyDrive/36106/assignment/AT3/data

---
## Student Information

In [ ]:
# <Student to fill this section>
group_name = "Group 20"
student_name = "Ratnadeep Patra"
student_id = "26294153"

In [ ]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [ ]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [ ]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [ ]:
# <Student to fill this section>

### 0.b Import Packages

In [ ]:
# <Student to fill this section>
import pandas as pd
import altair as alt

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

---
## B. Data Understanding

In [ ]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "product_category.csv")
except Exception as e:
  print(e)

### B.1 Explore Dataset

In [ ]:
pd.set_option('display.max_columns', None) # Forcing pandas to display all columns
pd.set_option('display.max_rows', None) # Forcing pandas to display all rows

In [ ]:
df.describe(include='all').T

                    count unique                                   top freq
product_category_id     4      4  6b440a50-1a1b-4d3b-988f-076c498bd092    1
name                    4      4                                 Bikes    1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_category_id  4 non-null      object
 1   name                 4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

In [ ]:
df['name']

0          Bikes
1     Components
2       Clothing
3    Accessories
Name: name, dtype: object

In [ ]:
# <Student to fill this section>
dataset_insights = """
This dataset contains 4 entries and 2 columns - 'product_category_id' and 'name'. Both columns are of object (string) data type. Each row represents a
unique product category. The four categories are: Bikes, Components, Clothing, and Accessories.
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `product_category_id`

In [ ]:
for csv_file in os.listdir(at.folder_path):
    if 'product_category_id' in pd.read_csv(at.folder_path / csv_file).columns:
        print(csv_file)

product_category.csv
product_sub_category.csv

In [ ]:
# <Student to fill this section>
feature_1_insights = """
The 'product_category_id' column serves as a unique identifier for each product category within this dataset. Its primary utility lies in its ability to
act as a foreign key for joining with 'product_sub_category.csv'. This allows for more comprehensive investigations into the hierarchical structure of
products, enabling analysis at a more granular level. By joining these datasets, one can explore relationships between broader categories and their
specific sub-categories, or analyze sales and product performance across different categorical levels.
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)